version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb+srv://lenchoajema:[password]@cluster0.teaih.mongodb.net/telemedicine_test?retryWrites=true&w=majority
      - JWT_SECRET=your_secure_jwt_secret_key_12345
      - LOG_ROUTES=false
      - FRONTEND_URL=http://localhost:5173
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
