version: "3.8"

services:
  mongodb:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017/telemedicine}
      - JWT_SECRET=your_secure_jwt_secret_key_12345
      - LOG_ROUTES=false
      - CLIENT_URL=${CLIENT_URL:-http://localhost:5173}
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:5000/api}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
