version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: telemedicine
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/telemedicine
      - JWT_SECRET=your_secure_jwt_secret_key_12345
      - USE_API_ROUTES=true
      - FRONTEND_URL=https://stunning-journey-wv5pxxvw49xh565g-5173.app.github.dev
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://stunning-journey-wv5pxxvw49xh565g-5000.app.github.dev
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
