[build]
  # Assumption: your frontend lives in `frontend/` and outputs to `build`
  # Change `frontend` and `build` below to match your repo layout.
  # Build from the frontend subdirectory (Vite)
  base = "frontend"
  # Use npm ci in the frontend base (requires package-lock.json). If you prefer
  # a looser install, change to `npm install && npm run build`.
  command = "npm ci && npm run build"
  publish = "dist"
  # functions path relative to the frontend base; functions live at repo/netlify/functions
  functions = "../netlify/functions"

[context.production.environment]
  # Example env var names used by the app; set actual values in Netlify site settings
  # SUPABASE_URL = ""
  # SUPABASE_ANON_KEY = ""
  # UPSTASH_REDIS_REST_URL = ""
  # UPSTASH_REDIS_REST_TOKEN = ""

[[_redirects]]
  # redirect /api/* to the proxy function
  [[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/proxy/:splat"
    status = 200
    force = true
