# Render service manifest for the telemedicine backend (Node, no Docker)

services:
  - type: web
    name: telemedicine-backend
    runtime: node
    plan: free
    branch: netlify-deploy
    rootDir: backend
    healthCheckPath: /api/health
    # Render provides PORT automatically; app must listen on process.env.PORT
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add secrets like MONGO_URI, JWT_SECRET, SMTP_* in Render as protected env vars
